# Site Identity
title: Gitslate
author: Your Name
description: A clean, slate-like reading experience.

# Defaults
defaults:
  - scope:
      path: "" # applies to all files in the repo
    values:
      layout: "default" # Now you don't even need to write 'layout: default' in every file!

# UI Labels (Configurable without touching HTML)
ui:
  theme_button: "Switch Mode"
  menu_header: "Gitslate"
  default_section_label: "Links"

# Jekyll Settings
remote_theme: jekyll/minima
data_source: .
